language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: required
      dist: trusty
    - os: osx
      compiler: clang

cache:
  directories:
    - $HOME/3rd_party

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install autoconf-archive; else sudo apt-get -y install autoconf-archive; fi
  - sed -i -e 's|AC_PREREQ(\[2.69\])|AC_PREREQ([2.68])|' configure.ac
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi

install:
  - export SDL_VERSION="2.0.4"
  - export SDL_PREFIX="$HOME/3rd_party/${TRAVIS_OS_NAME}/SDL_${SDL_VERSION}"
  - export PKG_CONFIG_PATH="$SDL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export PATH="$SDL_PREFIX/bin:$PATH"
  - |
    if [ ! -d "$SDL_PREFIX" ]; then
      mkdir -p "$SDL_PREFIX" && \
        wget https://www.libsdl.org/release/SDL2-${SDL_VERSION}.tar.gz -O - | tar -xz && \
        (cd SDL2-${SDL_VERSION} && \
          ./configure --prefix=$SDL_PREFIX && \
          make -j5 && make install)
    fi

  - export SDL_MIXER_VERSION="2.0.1"
  - export SDL_MIXER_PREFIX="$HOME/3rd_party/${TRAVIS_OS_NAME}/SDL_mixer_${SDL_MIXER_VERSION}"
  - export PKG_CONFIG_PATH="$SDL_MIXER_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export PATH="$SDL_MIXER_PREFIX/bin:$PATH"
  - |
    if [ ! -d "$SDL_MIXER_PREFIX" ]; then
      mkdir -p "$SDL_MIXER_PREFIX" && \
        wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-${SDL_MIXER_VERSION}.tar.gz -O - | tar -xz && \
        (cd SDL2_mixer-${SDL_MIXER_VERSION} && \
          ./configure --prefix=$SDL_MIXER_PREFIX && \
          make -j5 && make install)
    fi

  - export XMP_VERSION="4.4.1"
  - export XMP_PREFIX="$HOME/3rd_party/${TRAVIS_OS_NAME}/XMP_${XMP_VERSION}"
  - export PKG_CONFIG_PATH="$XMP_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
  - |
    if [ ! -d "$XMP_PREFIX" ]; then
      mkdir -p "$XMP_PREFIX" && \
        wget https://sourceforge.net/projects/xmp/files/libxmp/${XMP_VERSION}/libxmp-${XMP_VERSION}.tar.gz -O - | tar -xz && \
        (cd libxmp-${XMP_VERSION} && \
          ./configure --prefix=$XMP_PREFIX && \
          make -j5 && make install)
    fi

  - git clone https://github.com/google/styleguide.git ./styleguide
  - export CPPLINT_PATH="$PWD/styleguide/cpplint"

script:
  - $CPPLINT_PATH/cpplint.py ./src/*.cc ./src/*.h ./tests/*.cc ./windows/*.cc ./windows/*.h
  - ./bootstrap && ./configure --enable-sdl2-mixer
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then make dist-osx; else make -j5 distcheck; fi

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "freeserftest1"
