language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
    - os: osx
      compiler: clang

cache:
  directories:
    - $HOME/3rd_party

install:
  - export BUILD_DIR="$HOME/target"
  - mkdir $BUILD_DIR

  - export SDL_VERSION="2.0.5"
  - export SDL2DIR="$HOME/3rd_party/${TRAVIS_OS_NAME}/SDL_${SDL_VERSION}"
  - export PKG_CONFIG_PATH="$SDL2DIR/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export PATH="$SDL2DIR/bin:$PATH"
  - |
    cd $BUID_DIR
    if [ ! -d "$SDL2DIR" ]; then
      mkdir -p "$SDL2DIR" && \
        wget https://www.libsdl.org/release/SDL2-${SDL_VERSION}.tar.gz -O - | tar -xz && \
        (cd SDL2-${SDL_VERSION} && \
          ./configure --prefix=$SDL2DIR && \
          make -j5 && make install)
    fi

  - export SDL_MIXER_VERSION="2.0.1"
  - export SDL2MIXERDIR="$HOME/3rd_party/${TRAVIS_OS_NAME}/SDL_mixer_${SDL_MIXER_VERSION}"
  - export PKG_CONFIG_PATH="$SDL2MIXERDIR/lib/pkgconfig:$PKG_CONFIG_PATH"
  - export PATH="$SDL2MIXERDIR/bin:$PATH"
  - |
    cd $BUID_DIR
    if [ ! -d "$SDL2MIXERDIR" ]; then
      mkdir -p "$SDL2MIXERDIR" && \
        wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-${SDL_MIXER_VERSION}.tar.gz -O - | tar -xz && \
        (cd SDL2_mixer-${SDL_MIXER_VERSION} && \
          ./configure --prefix=$SDL2MIXERDIR && \
          make -j5 && make install)
    fi

  - export XMP_VERSION="4.4.1"
  - export XMPDIR="$HOME/3rd_party/${TRAVIS_OS_NAME}/XMP_${XMP_VERSION}"
  - export PKG_CONFIG_PATH="$XMPDIR/lib/pkgconfig:$PKG_CONFIG_PATH"
  - |
    cd $BUID_DIR
    if [ ! -d "$XMPDIR" ]; then
      mkdir -p "$XMPDIR" && \
        wget https://sourceforge.net/projects/xmp/files/libxmp/${XMP_VERSION}/libxmp-${XMP_VERSION}.tar.gz -O - | tar -xz && \
        (cd libxmp-${XMP_VERSION} && \
          ./configure --prefix=$XMPDIR && \
          make -j5 && make install)
    fi

  - |
    cd $BUID_DIR
    git clone https://github.com/google/styleguide.git ./styleguide
  - export CPPLINT_PATH="$PWD/styleguide/cpplint"

script:
  - |
    cd $TRAVIS_BUILD_DIR
    $CPPLINT_PATH/cpplint.py ./src/*.cc ./src/*.h ./tests/*.cc
  - |
    cd $BUID_DIR
    cmake $TRAVIS_BUILD_DIR
    make
    make test
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then make package; else make package_source; fi

addons:
  artifacts:
    working_dir: $BUILD_DIR
    paths:
    - $(ls *.dmg | tr "\n" ":")
    - $(ls *.tar.* | tr "\n" ":")
    target_paths: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
