os: Visual Studio 2015

version: '{build}'

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

cache:
  - c:\tools\vcpkg\installed\

install:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-http-proxy.ps1'))

  # Install required packages
  - cmd: vcpkg install sdl2:%platform%-windows
  - cmd: vcpkg install sdl2-mixer:%platform%-windows
  - cmd: vcpkg install sdl2-image:%platform%-windows
  - cmd: vcpkg install libxmp-lite:%platform%-windows
  - cmd: cd c:\tools\vcpkg
  - cmd: vcpkg integrate install

  # Prepare for NMake
  - if "%platform%" == "x86" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%platform%" == "x64" call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%configuration%
  - cmd: nmake check_style
  - cmd: nmake
  - cmd: nmake test
  - cmd: nmake package

after_build:
  - ps: |
      Push-AppveyorArtifact FreeSerf-$env:PLATFORM-$env:CONFIGURATION.exe
